---
title: "Dampak HGBT"
author:
  - name: Krisna Gupta
    id: kg
    orcid: 0000-0001-8695-0514
    email: imade.krisna@poltekapp.ac.id
    affiliation: 
      - name: Politeknik APP Jakarta
        city: Jakarta
        url: www.poltekapp.ac.id
abstract: > 
  Di sini saya membahas soal isu-isu kontemporer dalam perdagangan internasional
bibliography: ref.bib
csl: apa.csl
citation: 
  container-title: Working paper
  type: article-journal
#  volume:  
#  issue:  
#  issued:
#  doi: 
#  url:
execute: 
  echo: false
format: 
  html: 
    code-fold: true
#    html-math-method: mathml
    theme: united
    mainfont: serif
#  pdf: default
#    toc: false
#    number-sections: true
#    colorlinks: true
#    documentclass: scrartcli
#    papersize: a4
  docx:
    toc: false
    number-sections: true
---

```{r}
#| warning: false
library(tidyverse)
library(readxl)
library(WDI)
library(fixest)
library(modelsummary)
```

## Data

Data dikumpulkan berdasarkan laporan tahunan.

## Hasil

```{r}
dat<-read_excel("dat/HGBT.xlsx",sheet="data")
dut<-read_excel("dat/wpi.xlsx")
dat<-dat|>inner_join(dut)
dat$L1<-dat$L/dat$WPI*100
dat$K1<-dat$K/dat$WPI*100
dat$V1<-dat$V/dat$WPI*100
dat$lL1<-log(dat$L1)
dat$lK1<-log(dat$K1)
dat$lV1<-log(dat$V1)
dat$lL<-log(dat$L)
dat$lK<-log(dat$K)
dat$lV<-log(dat$V)

datasummary(All(dat)~factor(HGBT)*(Mean+SD),data=dat)
```

```{r}
reg1<-feols(data=dat,lV~lK+lL+HGBT)
reg2<-feols(data=dat,lV~lK+lL+HGBT|Perusahaan)
reg3<-feols(data=dat,lV~lK+lL+HGBT|Perusahaan+Tahun)
reg4<-feols(data=dat,lV1~lK1+lL1+HGBT)
reg5<-feols(data=dat,lV1~lK1+lL1+HGBT|Perusahaan)
reg6<-feols(data=dat,lV1~lK1+lL1+HGBT|Perusahaan+Tahun)
```

```{r}
regtab<- list(
  "OLS" = reg1,
  "FE"  = reg2,
  "TWFE"=reg3
)
modelsummary(regtab,stars=TRUE)

regtab1<- list(
  "OLS" = reg4,
  "FE"  = reg5,
  "TWFE"=reg6
)
modelsummary(regtab1,stars=TRUE)
```

## References {.unnumbered}